/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import model.DownloaderModel;

/**
 *
 * @author xd
 */
public class DownloadBinView extends javax.swing.JFrame {

    /**
     * Creates new form DownloadBinnView
     */
    private JLabel title_jlabel;
    private JProgressBar progressBar;
    private JLabel progress_jlabel;
    private JLabel speed_jlabel;
    private DownloaderModel downloaderModel;
    
    public DownloadBinView(DownloaderModel downloaderModel) {
        initComponents();
        this.downloaderModel = this.downloaderModel;
        this.setTitle(downloaderModel.getDownload_bin_window_title());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        download_bin_jpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        download_bin_jpanel.setLayout(new javax.swing.BoxLayout(download_bin_jpanel, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(download_bin_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(download_bin_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    }
    
    public void createElements(String title_text){
        this.title_jlabel = new JLabel(title_text);
        Font font = new Font(this.title_jlabel.getFont().getName(), Font.BOLD, 20);
        this.title_jlabel.setHorizontalAlignment(SwingConstants.CENTER);
        this.title_jlabel.setFont(font);
        download_bin_jpanel.add(this.title_jlabel);
        
        this.progressBar = new JProgressBar();
        this.progressBar.setMinimum(0);
        this.progressBar.setMaximum(100);
        this.progressBar.setPreferredSize(new Dimension(50, this.progressBar.getPreferredSize().height));
        download_bin_jpanel.add(this.progressBar);
        
        this.progress_jlabel = new JLabel("Progress: 0%");
        download_bin_jpanel.add(this.progress_jlabel);
        
        this.speed_jlabel = new JLabel("Download Speed: 0 MB/s");
        download_bin_jpanel.add(this.speed_jlabel);
        
        JSeparator separator = new JSeparator();
        separator.setForeground(new Color(0, 0, 0, 0)); // Set the foreground color to transparent
        separator.setBackground(new Color(0, 0, 0, 0)); // Set the background color to transparent
        download_bin_jpanel.add(separator);
    }
    
    public void updateData(int progress, int speed){
        this.progressBar.setValue(progress);
        this.progress_jlabel.setText("Progress: "+Integer.toString(progress)+"%");
        this.speed_jlabel.setText("Download Speed: "+Integer.toString(speed)+" MB/s");
    }

    public JPanel getDownload_bin_jpanel() {
        return download_bin_jpanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel download_bin_jpanel;
    // End of variables declaration//GEN-END:variables
}
